@startuml AppointmentPresentationClasses

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

class AppointmentController <<controller>> #PaleGreen;line:Black;text:Black {
  - appointmentView: AppointmentView
  - appointmentService: IAppointmentService
  + AppointmentController(view, service)
  - opSchedule(): void
  - opReSchedule(): void
  - opSearchAppointment(): void
  - opExport(): void
  - opClearSchedule(): void
  - opClearReSchedule(): void
}

class AppointmentView <<view>> #SkyBlue;line:Black;text:Black {
  - txtPatientID: JTextField
  - txtPhoneNumber: JTextField
  - txtMedID: JTextField
  - cmbSpeciality: JComboBox
  - dateTimeSpinnerSchedule: JSpinner
  - txtReason: JTextField
  - txtAppointmentId: JTextField
  - tabScheduleInfo: JTable
  - dateTimeSpinnerReSchedule: JSpinner
  + getPatientID(): String
  + getPhoneNumber(): String
  + getMedID(): String
  + getEspecialidad(): String
  + getScheduleDate(): Date
  + getReScheduleDate(): Date
  + getReason(): String
  + getAppointmentId(): String
  + setMedID(id): void
  + setReScheduleDate(date): void
  + setReason(reason): void
  + setScheduleInfoTableModel(model): void
  + addScheduleListener(l): void
  + addReScheduleListener(l): void
  + addExportListener(l): void
  + addClearScheduleListener(l): void
  + addClearReScheduleListener(l): void
  + addSearchAppointmentListener(l): void
  + showDialog(message): void
}

' from application layer
interface IAppointmentService<Application Layer> <<interface>> #aliceblue;line:blue;line.dotted;text:gray {
  + opSchedule(appointment): Appointment
  + opReSchedule(appointment): boolean
  + opFindAppointment(id): Appointment
  + opCheckScheduleConflict(medId, dateTime): boolean
  + opListAll(): List<Appointment>
}

AppointmentController "1..1" -> "1..1" AppointmentView : use
AppointmentController "1..1" -> "1..1" IAppointmentService : use

@enduml
