@startuml ApplicationOperationsClasses

interface IUserService <<interface>> #aliceblue;line:blue;text:blue {
  ' --- existente ---
  +verifyLogin(String username, String password): Role
  ' --- E1-HU1: Registrar Usuario ---
  +opCreateUser(ClsUser prmUser): ClsUser
  ' --- E1-HU2: Actualizar Usuario ---
  +opUpdateUser(ClsUser prmUser): boolean
  ' --- E1-HU3: Consultar Usuarios ---
  +opList(): List<ClsUser>
  +opGetUser(long id): ClsUser
  ' --- E1-HU4: Desactivar Usuario ---
  +opDeactivateUser(long id): boolean
}

class UserService <<service>> #PaleGreen;line:Black;text:Black {
  ' --- existente ---
  +verifyLogin(String username, String password): Role
  ' --- E1-HU1: Registrar Usuario ---
  +opCreateUser(ClsUser prmUser): ClsUser
  -validateCommonFields(ClsUser prmUser): void
  -validateRoleSpecificFields(ClsUser prmUser): void
  ' --- E1-HU2: Actualizar Usuario ---
  +opUpdateUser(ClsUser prmUser): boolean
  ' --- E1-HU3: Consultar Usuarios ---
  +opList(): List<ClsUser>
  +opGetUser(long id): ClsUser
  ' --- E1-HU4: Desactivar Usuario ---
  +opDeactivateUser(long id): boolean
}

@enduml
