@startuml DomainOperationsClasses

abstract User <<Abstract>> #Pink;line:Black;line.dotted;text:gray {
  <<Own>> #id: long 
  <<Own>> #username: String
  <<Own>> #fullname: String
  <<Own>> #password: String
  <<Own>> #role: Role
  <<Own>> #state: State
  <<Constructor>> + User(String username): void 
}

class Patient <<Entity>> #LightYellow;line:Black;text:Black {
  <<Own>> -citizenshipCard: long
  <<Own>> -phoneNumber: String
  <<Constructor>> +Patient(): void 
} 

abstract ClinicalStaff <<Abstract>> #Pink;line:Black;line.dotted;text:gray {
  <<Own>> #profession: Profession
  <<Own>> #specialty: Specialty
  <<Constructor>> +ClinicalStaff(): void
}

class Medic <<Entity>> #LightYellow;line:Black;text:Black {
  <<Constructor>> +Medic(): void
}

class Therapist <<Entity>> #LightYellow;line:Black;text:Black {
  <<Constructor>> +Therapist(): void
}

class AppointmentManager <<entity>> #LightYellow;line:Black;text:Black {
  <<Constructor>> +AppointmentManager(): void
}

class Administrator <<Entity>> #LightYellow;line:Black;text:Black {
  <<Constructor>> +Administrator(): void
}

class Appointment <<Entity>> #LightYellow;line:Black;text:Black {
  -id: long
  -citizenshipCardPatient: long
  -phoneNumberPatient: String
  -medicalStaffId: long
  -dateAndTime: Date 
  -attentionType: AttentionType
  <<Constructor>> +Appointment(): void
}

class ClinicEvent<public final class> <<Oserver Pattern>> #PaleGreen;line:Black;text:Black {
  +type: ClinicEventType
  +message: String
  <<Constructor>> + ClinicEvent(ClinicEventType type, String message): void
  <<Getter>> +getType(): ClinicEventType
  <<Getter>> +getMessage(): String
}

class ClinicEventBus <<Observer Pattern>> #PaleGreen;line:Black;text:Black {
  <<Associative>> -observers: List<ILibraryObserver>
  +subscribe(IClinicObserver observer) : void
  +unsubscribe(IClinicObserver observer) : void
  +publish(ClinicEvent event) : void
}

interface IClinicObserver <<Interface>> #aliceblue;line:blue;text:blue {
  onEvent(ClinicEvent event) : void
}

@enduml