@startuml DomainPackages

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

package "domain" {
  package "entities" {}
  package "enums" {}
  package "exceptions" {}
  package "core" {
    package "events" {}
  }
}

entities ..> enums

@enduml